name: Node.js CI

on:
  push:
    branches:
      - '**'
      - '!test/*'
  pull_request:
    branches:
      - '**'
      - '!test/*'

jobs:
  quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Run prettier check
        run: npm run prettier:check

      - name: Run lint
        run: npm run lint

  build:
    needs: quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present